set(ENGINE_PATH ${CMAKE_CURRENT_LIST_DIR})

function(group_sources_by_folder target)
  set(SOURCE_GROUP_DELIMITER "/")
  set(last_dir "")
  set(files "")

  get_target_property(sources ${target} SOURCES)

  foreach(file ${sources})
    file(RELATIVE_PATH relative_file "${PROJECT_SOURCE_DIR}" ${file})
    get_filename_component(dir "${relative_file}" PATH)
    if(NOT "${dir}" STREQUAL "${last_dir}")
      if(files)
        source_group("${last_dir}" FILES ${files})
      endif()
      set(files "")
    endif()
    set(files ${files} ${file})
    set(last_dir "${dir}")
  endforeach()

  if(files)
    source_group("${last_dir}" FILES ${files})
  endif()
endfunction()

macro(add_module name)
    message("Adding module <" ${name} ">")
    add_subdirectory(${ENGINE_PATH}/engine/${name} ${name})
endmacro()

macro(add_platform name)
    message("Adding platform <" ${name} ">")
    add_subdirectory(${ENGINE_PATH}/platform/${name} ${name})
endmacro(add_platform)